---
title: "CS598PSL Project 4"
author: "Akshay Nair"
date: "2022-12-03"
output: html_document
---

## Setup
```{r}
library(recommenderlab)
library(slam)
myurl = "https://liangfgithub.github.io/MovieData/"
ratings = read.csv(paste0(myurl, 'ratings.dat?raw=true'), 
                   sep = ':',
                   colClasses = c('integer', 'NULL'), 
                   header = FALSE)
colnames(ratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
i = paste0('u', ratings$UserID)
j = paste0('m', ratings$MovieID)
x = ratings$Rating
tmp = data.frame(i, j, x, stringsAsFactors = T)
Rmat = sparseMatrix(as.integer(tmp$i), as.integer(tmp$j), x = tmp$x)
rownames(Rmat) = levels(tmp$i)
colnames(Rmat) = levels(tmp$j)
Rmat = new('realRatingMatrix', data = Rmat)

train = Rmat[1:500, ]
test = Rmat[501, ]

```

## UBCF

### Generate Prediction
```{r}
trains <- as(train, "matrix")
tests = as(test, "matrix")
mean_trains = rowMeans(trains, na.rm = TRUE)
mean_tests = mean(tests, na.rm = TRUE)
S = proxy::simil(trains - mean_trains, tests - mean_tests, method = "cosine")
S = (1 + S) / 2
top_S = S[order(-S)[1:20], , drop = FALSE]

top_trains = merge(data.frame(trains - mean_trains), top_S, by = 'row.names', all = FALSE)
rownames(top_trains) = top_trains[,1]
top_trains = top_trains[,-1]
mypred = colSums(t(apply(top_trains, 1, function(x) { x[length(x)] * x[-length(x)] })), na.rm = TRUE)
mypred = mypred / sum(top_trains[,ncol(top_trains)])
mypred[mypred == 0] = NA
mypred[is.infinite(mypred)] = NA
mypred[tests != 0] = NA
mypred = mypred + mean_tests

```

### Compare to RecommenderLab
#### NA is the same
```{r}
recommender.UBCF <- Recommender(train, method = "UBCF",
                                parameter = list(normalize = 'center', 
                                                 method = 'Cosine', 
                                                 nn = 20))

p.UBCF <- predict(recommender.UBCF, test, type="ratings")
p.UBCF <- as.numeric(as(p.UBCF, "matrix"))

sum(is.na(p.UBCF) != is.na(mypred))
```

#### Predictions are close
```{r}
max(abs(p.UBCF - mypred), na.rm = TRUE)  ### should be less than 1e-06 
```

## IBCF
### Generate Prediction
```{r}

```


### Compare to RecommenderLab
#### NA is the same
```{r}
recommender.IBCF <- Recommender(train, method = "IBCF",
                                parameter = list(normalize = 'center', 
                                                 method = 'Cosine', 
                                                 k = 30))

p.IBCF <- predict(recommender.IBCF, test, type="ratings")
p.IBCF <- as.numeric(as(p.IBCF, "matrix"))

## first output: should be less than 10
sum(is.na(p.IBCF) != is.na(mypred))  
```

#### Predictions are close
```{r}
## second output: should be less than 10%
mydiff = abs(p.IBCF - mypred)
sum(mydiff[!is.na(mydiff)] > 1e-6) / sum(!is.na(mydiff)) 
```
